name: Test Called Workflow

on:
  workflow_call:
    inputs:
      opentofu_test_args:
        required: false
        type: string
      opentofu_test_verbose:
        required: false
        type: boolean
        default: false
      opentofu_version:
        required: true
        type: string
      working_directory:
        required: false
        type: string
        default: .

      # Uncomment if you have private modules

      # ssh_key:
      #   required: true

    secrets:
      opentofu_test_secret_args:
        required: false

permissions:
  contents: read

# If you use private modules, you'll need this env variable to use
# the same ssh-agent socket value across all jobs & steps.

# env:
#  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  test:
    name: OpenTofu
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      # GitHub - Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # GitHub - Setup SSH for private module access
      # Uncomment if you have private modules

      # - name: Private module access
      #   run: |
      #     ssh-agent -a $SSH_AUTH_SOCK
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ssh_key }}" | tr -d '\r' | ssh-add -
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Setup OpenTofu
      # https://github.com/marketplace/actions/opentofu-setup-tofu

      - name: OpenTofu setup
        uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1.0.6
        with:
          tofu_version: ${{ inputs.opentofu_version }}

      - name: OpenTofu format
        run: tofu fmt -check -diff

      - name: OpenTofu initialize
        run: tofu init

      - name: OpenTofu validate
        run: tofu validate

      - name: OpenTofu test
        id: test
        run: |
          tofu test --verbose=${{ inputs.opentofu_test_verbose }} -no-color ${{ inputs.opentofu_test_args }} ${{ secrets.opentofu_test_secret_args }}

      - name: OpenTofu summary
        continue-on-error: true
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        env:
          TEST_STDOUT: ${{ steps.test.outputs.stdout }}
        with:
          script: |
            const testResults = process.env.TEST_STDOUT || 'No output available.';
            core.summary
              .addCodeBlock(testResults, 'hcl')
              .write();
